### ISSUE TITLE
03-03 - Rhythm's gonna get you

### ISSUE THREAD

**Issue by piercebhunt** [piercebhunt/assignments#11]
# Rhythm's gonna get you

For this project, we will model and create a database. We are starting a record
label company, and we a place to store our bands, albums, and eventually songs.
You are creating a console app that stores our information in a database.

## Objectives

- Practice working with SQL
- Practice working with ORMs (EF Core)

## Setup

Create a console that allows a user to store and manage the company's bands,
albums, and (eventually) songs.

## Top Tips

Although in reality an album could be done by more than one band, our system
will just have an album involving **one** band. That is, an album belongs to one
band.

### Explorer Mode

- [x] Create a database that stores `Albums`, and `Bands`. They should have the following properties, use your best judgment for types. (We will add foreign keys in the next step)

  - [x] Album
    - Id
    - Title
    - IsExplicit
    - ReleaseDate
  - [x] Band

    - Id
    - Name
    - CountryOfOrigin
    - NumberOfMembers
    - Website
    - Style
    - IsSigned
    - ContactName
    - ContactPhoneNumber

  - Add foreign keys to fulfill the following

    - [x] One Band has many Albums

  - [x] Create an interface to let the user:

    - [ ] Add a new band
    - [ ] View all the bands
    - [ ] Add an album for a band
    - [ ] Let a band go (update isSigned to false)
    - [ ] Resign a band (update isSigned to true)
    - [ ] Prompt for a band name and view all their albums
    - [ ] View all albums ordered by ReleaseDate
    - [ ] View all bands that are signed
    - [ ] View all bands that are not signed

### Adventure Mode

- [ ] Add the ability for an album to have many songs. **NOTE** a song will only belong to a single album. Even if the same-named song appears on different albums we'd have a second entry for it.

  - [ ] Song

    - Id
    - Title
    - Lyrics
    - Length
    - Genre

- [ ] Track the individual members of a band. Create a new table called
      `Musicians` and give it a many to many relationships with a Band
- Add the following queries
  - [ ] View albums in a genre
  - [ ] View all members of a band

### Epic Mode

- Add another entity that you feel would benefit the system. Update your ERD,
  tables and user interface to support it.

## Additional Resources

- [PostgreSQL Documentation](https://www.postgresql.org/docs/)

**Comment by piercebhunt** [comment]
https://github.com/huntpie/RecordLabel

**Comment by piercebhunt** [comment]
Your homework **03 - 03 - Rhythm's gonna get you** was marked: **Acceptable**


![hmmm..acceptable! ](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBSZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--dbf0839075b0c873bc9d53d1b39f6ae9204934b9/acceptable.gif)
> &ldquo;hmmm..acceptable! &rdquo;

**Comment by gstark** [comment]
The assignment really wanted you to create a menu system that continually offers the options to the user so they can manage their list of bands, etc.

Your code, however, does demonstrate you understand the basics of using C# classes to manage records in a database so I will accept this assignment as is.
